### ISSUE TITLE
led-mode temp_linked fails headless on NAS (AX120 DIGITAL)

### ISSUE THREAD

**Issue by juanito54jm-ux** [Lexonight1/thermalright-trcc-linux#130]
Device: AX120 DIGITAL (0416:8001)
OS: Debian 13, OpenMediaVault, no display
Problem: trcc led-mode temp_linked fails with error:
TrccApp.set_system() must be called before start_metrics_loop()
trcc led-sensor cpu works fine but led-mode always crashes headless.
trcc serve starts correctly but token changes on every restart making automation impossible.

**Comment by Lexonight1** [comment]
Thanks for the report — both halves should be addressed now.

**\`led-mode temp_linked\` failing headless** is fixed in **v9.4.10**. The CLI was running sensor-linked LED modes against a zeroed metrics snapshot because no metrics loop is started for one-shot CLI commands. The composition root now bootstraps \`SystemService\` once and seeds every connected device with current metrics before the command runs.

**\`trcc serve\` token rotating on every restart** — this should already be persistent on recent versions: the token is generated once and stored in \`~/.trcc/config.json\`, then reused forever. To narrow it down, could you confirm:
- which \`trcc-linux\` version you saw the rotation on (\`trcc --version\`)?
- that \`~/.trcc/config.json\` is writable by the user running \`trcc serve\` — under OMV the daemon often runs as a non-login user with a different \`\$HOME\`, which would cause a fresh config (and thus a fresh token) on every start?

If the rotation persists on v9.4.10 with a writable config, please paste the contents of \`~/.trcc/config.json\` after two restarts and I'll dig deeper.

**Upgrade**
- Debian / Ubuntu: \`wget -c https://github.com/Lexonight1/thermalright-trcc-linux/releases/latest/download/trcc-linux-latest_all.deb && sudo dpkg -i trcc-linux_*.deb\`
- Older Debian / glibc < 2.39: \`wget -c https://github.com/Lexonight1/thermalright-trcc-linux/releases/latest/download/trcc-linux-latest.legacy_all.deb && sudo dpkg -i trcc-linux_*.legacy_all.deb\`
- pip: \`pip install --upgrade trcc-linux\`

---
If this project helps you, consider [buying me a beer](https://buymeacoffee.com/Lexonight1) 🍺 or [Ko-fi](https://ko-fi.com/lexonight1) ☕

**Comment by Lexonight1** [comment]
Hi @juanito54jm-ux — gentle nudge. The `led-mode temp_linked` headless fix from v9.4.10 (CLI now bootstraps `SystemService` once and seeds metrics before the command runs) is intact in v9.5.2. v9.5.2 also adds the broader addr-threading regression coverage in case your AX120 DIGITAL was hitting any of the other issues I shipped today.

When you have a moment, would you confirm `led-mode temp_linked` works on v9.5.2? No urgency — just want to close the loop before marking the issue resolved.

Upgrade — pip install on the NAS or whichever distro you're on:
- pip: `pip install --upgrade trcc-linux`
- Distro packages at https://github.com/Lexonight1/thermalright-trcc-linux/releases/latest

Thanks for the patience while this got sorted.

---
If this project helps you, consider [buying me a beer](https://buymeacoffee.com/Lexonight1) 🍺 or [Ko-fi](https://ko-fi.com/lexonight1) ☕

**Comment by juanito54jm-ux** [comment]
Updated to v9.5.2. led-mode temp_linked no longer crashes headless — thank you! However the LED display still shows nothing. There is a new warning:
LED protocol error: 'DeviceInfo' object has no attribute 'addr'
LED mode: temp_linked is printed but nothing appears on the device.

**Comment by Lexonight1** [comment]
Hi @juanito54jm-ux — thanks for the report. The `TrccApp.set_system() must be called before start_metrics_loop()` error was a wiring bug in the headless command path; the daemon-mode rewrite that landed in v9.5.x changes how those services compose, and the global `TrccApp` singleton is being dissolved. Could you upgrade and try again? Debian 13:

```
wget -c https://github.com/Lexonight1/thermalright-trcc-linux/releases/latest/download/trcc-linux-latest_all.deb
sudo dpkg -i trcc-linux-latest_all.deb
trcc led-mode temp_linked
```

If it still crashes, paste the new traceback — the shape will be different now and that'll tell me where to look next.

The `trcc serve` token-changes-on-restart issue is real and separate — would you mind opening a focused ticket for that one? Pinning the token to a config file is the right fix; it just hasn't been done yet.

---
If this project helps you, consider [buying me a beer](https://buymeacoffee.com/Lexonight1) 🍺 or [Ko-fi](https://ko-fi.com/lexonight1) ☕

**Comment by Lexonight1** [comment]
Hi @juanito54jm-ux — I'm trying my best to get the AX120 fully working for you on the OMV NAS. The `LED protocol error: 'DeviceInfo' object has no attribute 'addr'` you saw on v9.5.2 should be sorted in v9.5.9. When you have a quiet moment:

```
wget -c https://github.com/Lexonight1/thermalright-trcc-linux/releases/download/v9.5.9/trcc-linux_9.5.9-1.legacy_all.deb
sudo dpkg -i trcc-linux_9.5.9-1.legacy_all.deb
```

Then `trcc led-mode temp_linked` — if the LED finally lights up, that's wonderful. If still nothing, please paste a few lines from `trcc.log` after the command and I'll dig in. Thanks for the patience on the headless side; it's a path I can't test without your help.

---
If this project helps you, consider [buying me a beer](https://buymeacoffee.com/Lexonight1) 🍺 or [Ko-fi](https://ko-fi.com/lexonight1) ☕

**Comment by juanito54jm-ux** [comment]
Summary of testing across v9.4.10 and v9.5.9-1.legacy — two separate bugs
Bug 1 (both versions): LED protocol error: 'DeviceInfo' object has no attribute 'addr'
Detected 1 device(s): Winbond LED Controller [led]
LED connect: using detected usb:3:2
get_protocol: cache miss for 0416_8001_usb:3:2 — creating
create_protocol: protocol=led
LED protocol error: 'DeviceInfo' object has no attribute 'addr'
send_colors: skipped (colors=10, protocol=False)
Device is detected correctly (0416:8001, usb:3:2) but create_protocol crashes and nothing is sent.
Bug 2 (v9.5.9-1.legacy only): crashes on boot before doing anything
TypeError: connect expected at least 6 arguments, got 5
  File "linux_platform.py", line 704, in subscribe_power
    bus.connect('org.freedesktop.login1', ...)
This is a regression — v9.5.9 is completely unusable on headless/NAS. Reverted to 9.4.10.
Environment: Debian 13, OMV NAS, headless, no desktop session, Python 3.13.

**Comment by Lexonight1** [comment]
Hi @juanito54jm-ux — going through your last comment one item at a time:

**Bug 1 (`'DeviceInfo' object has no attribute 'addr'`):** fixed. The `.addr` attribute was renamed to `usb_address` and routed through three sanctioned classmethods (`from_detected`, `from_dict`, `from_wire_dict`) in v9.5.10+. Current `src/` has zero references to the old name.

**Bug 2 (`subscribe_power` 5-arg crash on v9.5.9):** also fixed. The v9.5.9 regression where a bare Python callable was passed to QtDBus is gone — current code uses a QObject bridge with a `@Slot(bool)` method, which is the supported signature.

**Token persistence:** already shipped in v8.3.3. `trcc serve` generates the token on first run and reuses it forever (`Settings.get_api_token()` / `save_api_token()`). Same token across restarts now; automation works.

You're stuck on v9.4.10 — the AUR / Debian repos have moved a lot since then. Debian 13 upgrade:

```
wget -c https://github.com/Lexonight1/thermalright-trcc-linux/releases/download/v9.6.4/trcc-linux_9.6.4-1_all.deb
sudo dpkg -i trcc-linux_9.6.4-1_all.deb
```

Then `trcc led-mode temp_linked` on a fresh install — if the LED finally lights up, that's the goal. If anything new comes up on v9.6.4, `trcc report` and I'll dig in.

I'm one human maintainer here. The OMV NAS path is one I cannot test without your help, so genuinely thank you for the patience.

---
If this project helps you, consider [buying me a beer](https://buymeacoffee.com/Lexonight1) 🍺 or [Ko-fi](https://ko-fi.com/lexonight1) ☕

**Comment by juanito54jm-ux** [comment]
Hi, testing v9.6.4 via pipx on Debian 13 headless (OMV NAS).
Good news: trcc status now shows the LED connected correctly:
connected:   True
style id:    1
mode:        0
color:       rgb(255, 0, 0)
brightness:  65%
global on:   True
zones:       4
Bad news: it ends with a segmentation fault and the LED animation stops.
trcc led-mode temp_linked gives:
LED index 0 out of range (have 0)
Error: LED 0 not found
trcc led-debug fails with a circular import:
ImportError: cannot import name 'LedProtocol' from partially initialized module
led_protocol.py → factory.py → led_protocol.py
The LED physically reacts when I run trcc detect (animation freezes and stops), so the USB connection is working. But nothing persists after the command exits.
No rush at all — I really appreciate the incredible work you're putting into this project. Thank you so much! 🙏
